services:
  observability-demo:
    build: .
    ports:
      - "8080:8080"

  load-generator:
    build: ./load-generator
    environment:
      LOAD_GENERATOR_TARGET_BASE_URL: http://observability-demo:8080
    depends_on:
      - observability-demo
