spring:
  application:
    name: rounding-service

management:
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://otel-collector:4318/v1/logs
