spring:
  application:
    name: load-generator

management:
  otlp:
    metrics:
      export:
        url: http://otel-collector:4318/v1/metrics

load-generator:
  target-base-url: http://localhost:8080
  min-delay-ms: 200
  max-delay-ms: 3000
  min-value: 0
  max-value: 1000
